name: lab01
on: [push]
jobs: 
    test: 
        runs-on: ubuntu-latest
        steps: 
            - run: pip install nbconvert
            - uses: actions/checkout@v4
            - run: sudo apt-get install pandoc
            - run: python -m nbconvert lab1/lab1.ipynb