# name: lab01
# on: [push]
# jobs: 
#     test: 
#         runs-on: ubuntu-latest
#         steps: 
#             - run: pip install nbconvert ipykernel pint matplotlib scipy open-atmos-jupyter-utils
#             - run: sudo apt-get install pandoc inkscape texlive-xetex
#             - uses: actions/checkout@v4
#             - run: python -m nbconvert --to pdf --execute lab1/lab1.ipynb
#             - uses: actions/upload-artifact@v4
#               with:
#                 path: lab1/lab1.pdf

name: lab01

on:
  push:
    paths:
      - lab1/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pip packages
        run: |
          pip install --upgrade pip
          pip install nbconvert ipykernel pint matplotlib scipy open-atmos-jupyter-utils

      - name: Install APT packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc inkscape texlive-xetex

      - name: Execute and convert notebook to PDF
        run: |
          python -m nbconvert --to pdf --execute lab1/lab1.ipynb

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          path: lab1/lab1.pdf
